### ISSUE TITLE
First step: move all known issues for the existing TextMate grammar to this repo

### ISSUE THREAD

**Issue by daviwil** [PowerShell/EditorSyntax#1]
Since we're now centralizing development of the TextMate definition for PowerShell in this repo, it'd be good to find all known issues with the current state of the syntax definition and move them to this repo.  It'd be great to have some help doing this (especially if someone can find a way to automate it :wink:)

Here are some starting points:
### Visual Studio Code
- https://github.com/Microsoft/vscode/issues/3342
- [vscode-powershell issues with label `syntax-bug`](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aopen+is%3Aissue+label%3Asyntax-bug)
### Sublime Text
- Issues with label [area:Syntax](https://github.com/SublimeText/PowerShell/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%3ASyntax)
### Atom
- https://github.com/jugglingnutcase/language-powershell/issues/24

@guillermooo @jugglingnutcase @vors @Jaykul @gravejester

**Comment by hashhar** [comment]
I can try writing a script to import the issues. I will let you know within the week.

**Comment by jugglingnutcase** [comment]
I just used this application to do it: https://github-issue-mover.appspot.com/

Looks like it's run by @google: see the code in their org: https://github.com/google/github-issue-mover

It was pretty easy to migrate the issues with: someone with access to the original repo with issuess need to auth the app and then paste a couple links with the old issue and this repository.

**Comment by jugglingnutcase** [comment]
I'm fine with it closing the original issue on my repo, I guess other people may want a different behavior, though.

**Comment by hashhar** [comment]
@jugglingnutcase I'll try and see if I can manage to fork the repo to behave that way.

**Comment by hashhar** [comment]
I'm sorry but I couldn't get the tool to work that way. I'll have to write a script. Sorry for the delay.

**Comment by omniomi** [comment]
Closing as the vast majority of issues were indeed moved or resubmitted.
