### ISSUE TITLE
stop-parsing symbol doesn't stop PowerShell highlighting

### ISSUE THREAD

**Issue by keith-hall** [PowerShell/EditorSyntax#113]
### Environment

- Sublime 3176
- Monokai

### Issue Description

The [PowerShell "stop-parsing" symbol](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_parsing?view=powershell-6#long-description) is scoped correctly, but doesn't prevent the rest of the line being highlighted as PowerShell code.

#### Screenshots

![image](https://user-images.githubusercontent.com/11882719/40783168-50752ba8-64ea-11e8-8e8a-191704c9d6cd.png)

### Expected Behavior

The rest of the line following `--%` should be scoped as `string.unquoted` with no PowerShell constructs scoped like `$VarName` or `/`.

### Code Samples

```PowerShell
tf.exe status . /r --% /workspace:*;domain\$UserName
```
(code taken from https://stackoverflow.com/a/18928501/4473405)

**Comment by omniomi** [comment]
Just need to add a capture for anything until the end of the line and make sure the stop-processing symbol is high in the definitions.
