### ISSUE TITLE
Using Namespace will be shown as error

### ISSUE THREAD

**Issue by dotChris90** [PowerShell/EditorSyntax#115]
### Environment
- Visual Studio Code
- 1.23.1
- on Windows 10 x64 
- integrated Powershell for Debugging in VS Code 
![image](https://user-images.githubusercontent.com/33638852/40856910-bedf1cee-65d9-11e8-8606-d8d80726ed5f.png)

### Issue Description

- when using the "using namespace XYZ" Statement Visual Studio Code shows me an error
- it says sth about "before all other Statements in a script a using Statement is required" (sorry german operating System so with german powershell and german error. 

#### Screenshots

![image](https://user-images.githubusercontent.com/33638852/40856965-e805c8ac-65d9-11e8-8df3-dd72c9394b0b.png)

### Expected Behavior

do not Show error

**Comment by omniomi** [comment]
Hi there @dotChris90,

That's actually https://github.com/PowerShell/PSScriptAnalyzer that's doing the underlining not the syntax. The issue is that the `using` statements in PowerShell cannot have anything other than comments between them and the beginning of the file.

> The using statement needs to be the first statement in the script. - [About_Using](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_using?view=powershell-5.1)

You need to move the `Add-Type` line below the `using` statements. As it stands they're invalid and being ignored.

**Comment by dotChris90** [comment]
@omniomi 

thanks for that. it works. I did not know Powershell was truely able to using a Namespace before the DLL was loaded into the scope of it. ;)

Thanks you a lot. 
Wish you a nice Weekend.

**Comment by vors** [comment]
I think you need just replace `add-type` by `using assembly` to bring it into the session.

**Comment by dotChris90** [comment]
thanks for advice but the Add-Type works fine. Just the red lines was weird to me because I though powershell just can using namespaces of imported DLLs but .... nope. You can put the add-type at the end and all is fine. ^^
