### ISSUE TITLE
".role" in a comment does not highlight correctly

### ISSUE THREAD

**Issue by Blackbaud-ShaydeNofziger** [PowerShell/EditorSyntax#119]
### Environment

- Editor and Version (VS Code, Atom, Sublime): VSCode, 1.25.0-insiders (Commit: 7dc9539a421c9c33e57e2ce0b718f183bb44c756)
- Your primary theme: DefaultDark (issue occurs in all themes)

### Issue Description

If a comment string contains `.Role` or `.role`, the word "role" is colored incorrectly.

#### Screenshots

![image](https://user-images.githubusercontent.com/12850455/41483914-e4744810-70a8-11e8-8512-dc773cec1f42.png)

### Expected Behavior

`.role`/`.Role` should remain green/the color of the comments.

### Code Samples

```PowerShell
# This role works
# This .Role doesn't work
# This .role doesn't work
# $MachineParts.RoleCode
```

**Comment by omniomi** [comment]
Looks like we missed a negative lookbehind for words in front of `comment.documentation.embedded.powershell` within the `commentEmbeddedDocs` repository section. The match should ensure nothing but white space or the `#` symbol between the beginning of the line and the `.`.

Good catch, will fix; Thanks.
