### ISSUE TITLE
brace wrapping variable tends to have no theme

### ISSUE THREAD

**Issue by msftrncs** [PowerShell/EditorSyntax#128]
### Environment

- Editor and Version: VS Code: 1.25.1
- Your primary theme: Dark+ (with corrections for punctuation inside subexpressions inside strings)

### Issue Description
Braces tend not to get themed in general.  PowerShell ISE colors the braces that wrap a variable (complex variable name) with the same color as the variable.  Good or bad, I think the braces that wrap variable names should be scoped something different, so that coloring could be chosen based on that.  For instance, I would think coloring the braces wrapping a variable the same color as the $ token would be ideal (and I swear this was the case at one time).  (scope 'keyword.other.variable.definition.powershell')

I added coloring to insure that the punctuation inside a subexpression inside a string appeared as if it was any other expression and not text,  While doing that, I think I worked around not having a more specific scope.

```json
{
    "editor.tokenColorCustomizations": {
        "[Default Dark+]": {
            "textMateRules": [
                {
                    "scope": [
                        "punctuation.section.group.begin.powershell",
                        "punctuation.section.group.end.powershell",
                        "punctuation.section.bracket.begin.powershell",
                        "punctuation.section.bracket.end.powershell",
                        "meta.scriptblock.powershell punctuation.section.braces.begin.powershell",
                        "meta.scriptblock.powershell punctuation.section.braces.end.powershell"
                    ],
                    "settings": {
                        "foreground": "#d4d4d4"
                    },
                },
                {
                    "scope": [
                        "punctuation.section.braces.begin.powershell",
                        "punctuation.section.braces.end.powershell"
                    ],
                    "settings": {
                        "foreground": "#569cd6"
                    }
                }
            ]
        }
    }
}
```

### Code Samples

This is just a sample of what I was checking scopes on: (the braces are not necessary)
```PowerShell
"...Reduced block '$($datablock.name)' by $($orgDataLength-$(${datablock}.value.Length))) bytes."
```

**Comment by msftrncs** [comment]
I quickly determined the work around failed inside a script block:

![image](https://user-images.githubusercontent.com/26179051/43988719-2fa78b06-9d01-11e8-9030-a8581ee6a717.png)

![image](https://user-images.githubusercontent.com/26179051/43988724-437ff6e0-9d01-11e8-8d2d-2d209e785a6c.png)

**Comment by msftrncs** [comment]
With the release of VS Code 1.26, the above issue with the braces went away, they now color with the variable as they have been moved in to the same scope with the variable, as has the $ preceding the variable, which used to be scoped separately as a keyword, but the $ that marks the subexpression, now lacks any themed scope, and so when in a string, it now themes as a string.   That's a different issue...  this issue can probably be considered closed.

**Comment by omniomi** [comment]
@msftrncs the sigil on variables remains scoped separately as `punctuation.definition.variable.powershell` (this is in line with batch, go, less, bash, make, perl, php, ruby, and vb.net) the difference now is that the variable scope is now a parent to the variable from boundry to boundry of the whole variable. Themes that support `punctuation.definition.variable`, `punctuation.definition`, or `punctuation` will still show a colour different from the variable name but now themes that don't  will use the variable scope to colour the sigil instead of the default foreground colour thus making it uniform. 

From the default themes Dark+ will show the new parent at work while Kimbie Dark will show the sigil is still distinct should the theme cover it. 

This behaviour is now consistent with most other variable sigil baring languages.

**Comment by msftrncs** [comment]
@omniomi, the change to the punctuation scope does upset the PowerShell ISE theme in VS Code, as it has a deliberate color applied to punctuation, which alleviates the string subexpression issue, but now the '$' for the variable colorizes different than PowerShell ISE would normally (VS Code 1.25.1 and earlier).  I don't know if that is something simple reordering of the theme definitions can resolve.
