### ISSUE TITLE
subexpression marker ($ in '$(') is in scope 'punctuation.definition.variable'

### ISSUE THREAD

**Issue by msftrncs** [PowerShell/EditorSyntax#132]
### Environment

- Editor and Version: VS Code: 1.26.0
- Your primary theme: Dark+

### Issue Description

The subexpression marker(the $ in '$(') is currently scoped in 'punctuation.definition.variable'.  This causes no colorization in most schemes, such then cause colorization issues in double quoted text subexpressions.

### Expected Behavior

I might think that it should be in a 'keyword' scope.   To play around, I modified the VS Code powershell.tmLanguage.json file, in two places, to change the $ in '$(' to be scoped as 'keyword.other.subexpression.powershell'.

This seems to get the result with themes, causing it to colorize the same as the @ in '@(' or '@{' which also scope as a 'keyword'.

**Comment by vexx32** [comment]
@TylerLeonhardt would be great to have something along these lines tbh, this is such a common thing in a lot of code I see and it can look really weird in strings at the moment. 😔

**Comment by msftrncs** [comment]
Related items: #106, #59 

@vexx32, in a recent PR #156 commit, I have set the `${` and `}` of an interpolation (not a substatement) to  scope as 'punctuation.section.embedded.begin/end.powershell'.  Some editors/themes then have a highlight for that.  See #59 above,  I've been considering added a PR to get this handled... but I think I was running into the issue that substatement and interpolated substatement are handled in the same rule, would get same scopes, and so I would need to separate that out.  That's what I did in PR #156, so I suppose that's inevitable.  There was also some naming issues around some of those rules, which lead to confusion.

Would the `punctuation.section.embedded` scope be better than just `keyword.other`?  I found the themes in VS Code supported the embedded scope for some other languages, but not PowerShell.  Atom on the other hand appears to support the scope in all languages in the default theme.

It might be possible to apply both scopes to the interpolated version of the definition, then support in the theme can fallback to which ever is supported.

**Comment by vexx32** [comment]
Hard to say from where I'm standing, I'm afraid. I'm not super familiar with how the different scopes are handled, but I'm painfully aware that a lot of themes have a bit of inconsistent support for many of the scope rules.

I guess it seems logical that if we can apply multiple that are sensible, at least one of them is likely to be covered by a given theme?

**Comment by msftrncs** [comment]
I've partially misspoke, I just found out that while VS Code's Monokai Dimmed does not highlight punctuation.section.embedded, the default Dark+/Light+ themes do.

My goal is still to try to post a small PR for this and related issues.

**Comment by msftrncs** [comment]
Disappointingly ATOM does not support specifying multiple scopes. This means that the tests in this project will fail since they are based on ATOM.   :(

**Comment by msftrncs** [comment]
I think I found a work-around for the ATOM issue.

VS Code:
![image](https://user-images.githubusercontent.com/26179051/63151988-662f7600-bfd0-11e9-86d6-cf4dddd52e66.png)

ATOM:
![image](https://user-images.githubusercontent.com/26179051/63152022-7b0c0980-bfd0-11e9-9117-dc4449326530.png)
