### ISSUE TITLE
grammar freezes

### ISSUE THREAD

**Issue by aeschli** [PowerShell/EditorSyntax#134]
Opening this [file](https://github.com/larssb/HealOps/blob/master/Deployment/Install-HealOps.ps1) freezes with the latest grammar.

I reverted the VSCode grammar to https://github.com/PowerShell/EditorSyntax/commit/6f5438611c54922ea94c81532a2dcfee72190039

**Comment by omniomi** [comment]
The difference between the two versions was  `(?i:\s*(\.)` - > `^(?i:(?:\s*|#)+(\.)` reason being if you forgot a space after a sentence and had a keyword it would highlight (#119). The `*` has been there all along but coupled with the `+`  that's what's doing it in. Whether you change it to `^(?i:(?:\s?|#)+(\.)` or `^(?i:(?:\s*|#)(\.)` the crash stops.

They probably went with `\s*` originally to cover tabs/spaces but it should really be `\S?`. I will push that ASAP.

**Comment by msftrncs** [comment]
Quick correction:  The `^` should be changed to `(?:^|\\G)`, as get-help allows the keyword on the same line as the start of the multiline comment, but with nothing other than spaces between.

**Comment by msftrncs** [comment]
and a final correction, I completely missed the first point I brought up, get-help doesn't allow anything trailing on the keyword lines that do not pass an argument for the help keyword.

Add `(?:\\s$)` to the end of the matches with only two captures.

**Comment by Jaykul** [comment]
@msftrncs probably should open a separate issue to track that.
