### ISSUE TITLE
Comma and Periods break Highlighting inside of Quotes.

### ISSUE THREAD

**Issue by gerane** [PowerShell/EditorSyntax#14]
This just started happening in the latest Code Insiders 7/27

Sample Code

``` powershell
if ($ModuleResults)
{
    if ($ModuleResults.Installed -ne $null)
    {
        Write-Host "[INFO] " -ForegroundColor DarkMagenta -NoNewline
        Write-Host "Installed Modules: "  -NoNewLine -ForegroundColor Gray 
        Write-Host "$($ModuleResults.Installed -join ', ')" -ForegroundColor DarkGray
    }

    if ($ModuleResults.Updated -ne $null)
    {
        Write-Host "[INFO] " -ForegroundColor DarkMagenta -NoNewline
        Write-Host "Updated Modules: " -NoNewLine -ForegroundColor Gray 
        Write-Host "$($ModuleResults.Updated -join ', ')" -ForegroundColor DarkGray
    }

    if ($ModuleResults.FailedUpdate -ne $null)
    {
        Write-Host "[Error] " -ForegroundColor Red -NoNewline
        Write-Host "Module Update Failed: " -NoNewLine -ForegroundColor Gray 
        Write-Host "$($ModuleResults.FailedUpdate -join ', ')" -ForegroundColor DarkGray
    }

    if ($ModuleResults.FailedInstall -ne $null)
    {
        Write-Host "[ERROR] " -ForegroundColor Red -NoNewline
        Write-Host "Module Install Failed: " -NoNewLine -ForegroundColor Gray 
        Write-Host "$($ModuleResults.FailedInstall -join ', ')" -ForegroundColor DarkGray
    }
}
```

Here is how it looks by default

![syntaxquotes](https://cloud.githubusercontent.com/assets/6662208/17175983/2900309a-53d0-11e6-82ec-834fdb94ef82.png)

If I remove the dot in `$ModuleResults.Installed` it clears up.

![syntaxnoperiod](https://cloud.githubusercontent.com/assets/6662208/17175988/2fd94456-53d0-11e6-8f2a-b82e1b7c1fb1.png)

If I remove the comma inside of the quotes, you can see that it clears up the rest of the syntax outside of the double quotes, but the `-join ' '` is still wrong.

![syntaxnocomma](https://cloud.githubusercontent.com/assets/6662208/17176000/38bf68d4-53d0-11e6-9171-3d9eac48b993.png)

Removing the double quotes still has all following syntax broken.

![syntaxnodouble](https://cloud.githubusercontent.com/assets/6662208/17175995/35e3f10c-53d0-11e6-861f-f5c71cebeb15.png)

**Comment by omniomi** [comment]
Fixed by #94
