### ISSUE TITLE
PS v6 approved verb highlighting

### ISSUE THREAD

**Issue by Akaizoku** [PowerShell/EditorSyntax#147]
The list of approved verb has been updated in PowerShell v6 to include the following verbs:

Verb (alias) | Action | Comments
-- | -- | --
Build (bd) | Creates an artifact (usually a binary or document) out of some set of input files (usually source code or declarative documents) | This verb was added in PowerShell v6
Deploy(dp) | Sends an application, website, or solution to a remote target[s] in such a way that a consumer of that solution can access it after deployment is complete | This verb was added in PowerShell v6

Could it be possible to add highlighting for those new verbs?

```powershell
$foo = Build-Foo
$foo = Deploy-Foo
$foo = Get-Foo
```

**Comment by tylerl0706** [comment]
@Akaizoku those verbs should have syntax highlighting (see my addition to your question). Are you seeing otherwise? If so, can you share a screenshot or something?

**Comment by Akaizoku** [comment]
@tylerl0706 I can see it properly highlighted here, but not on Atom which is using the [`language-powershell`](https://atom.io/packages/language-powershell) package.

On the [package repository](https://github.com/jrsconfitto/language-powershell) it is written:

> If you discover any issues with the way the syntax is highlighted, please open an issue against the [PowerShell/EditorSyntax](https://github.com/PowerShell/EditorSyntax) repository instead of this one, since this package is based on that grammar.

This is the reason I opened the issue here.
