### ISSUE TITLE
Commented out text still uncommented

### ISSUE THREAD

**Issue by PrzemyslawKlys** [PowerShell/EditorSyntax#148]
### Environment

- Editor and Version (VS Code, Atom, Sublime): VSCode
- Your primary theme: Monokai

### Issue Description

Pasting code as below shows .Link as still active

![image](https://user-images.githubusercontent.com/15063294/46164634-d638ee80-c28e-11e8-8c50-527c70ca1156.png)

```powershell
#write-host $link.Text
#write-host $link.Link
```
### Expected Behavior

Commented out - same color

**Comment by msftrncs** [comment]
This is related to #136, documentation keywords being detected where not eligible or not detected where they should be (though it focuses on the not being detected part). 

` # .link` is a documentation keyword that allows HELP to present useful links to the user.  Its only supposed to be eligible when used at the start of a single line comment that starts a line or at the start of any line in a multi line comment.

**Comment by omniomi** [comment]
@PrzemyslawKlys, this was actually fixed in PR #135. It hasn't been merged into Microsoft/vscode yet but should be soon.

You can use the latest build artifact if you would like the fix now: https://ci.appveyor.com/project/powershell/editorsyntax/branch/master/artifacts

**Comment by PrzemyslawKlys** [comment]
Thanks. I'll wait for official release :-) Not really big deal.
