### ISSUE TITLE
Double-quoted strings treat @tokens as interpolations

### ISSUE THREAD

**Issue by NReilingh** [PowerShell/EditorSyntax#149]
### Environment

- Editor and Version (VS Code, Atom, Sublime): VS Code 1.29.0
- Your primary theme: Dark+ (default dark)

### Issue Description

Double-quoted strings color `@tokens` the same as `$tokens`

#### Screenshots

![image](https://user-images.githubusercontent.com/2458645/48501191-9f04a980-e80a-11e8-8c1e-015f882ac127.png)

### Expected Behavior

Only `$tokens` or `$(expressions)` are string-interpolated in a double-quoted string. The `@word` is just going to be treated as part of the string.

### Code Samples

This may be an appropriate spec test case:

```PowerShell
    "This is a @double quoted string."
#   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ string.quoted.double.powershell
```

**Comment by msftrncs** [comment]
This has been mentioned in #137.

**Comment by msftrncs** [comment]
I was looking at the possible test case, but I don't think it is sufficient, but I may not entirely understand how the test works.  In my mind, the entire string will scope as spec'd, regardless of whether the `@double` scopes as a splat or not.

**Comment by msftrncs** [comment]
Looks like this is needed?

```PowerShell
# @splat references only work in argument mode, should not highlight in strings.
"This is a @double quoted string."
# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ string.quoted.double.powershell
#           ^ not:variable.other.readwrite.powershell
```

**Comment by TylerLeonhardt** [comment]
That seems right, @msftrncs. I would recommend running the test before and after your change to see if it fixes the test.
