### ISSUE TITLE
Syntax highlighting problem with ValidateScript parameter attribute

### ISSUE THREAD

**Issue by pcgeek86** [PowerShell/EditorSyntax#17]
# Issue

The `[ValidateScript({ ... })]` parameter attribute is commonly used to perform customized validation on parameter values that a caller passes into a PowerShell function. In Visual Studio Code `1.4.0`, running on Windows 10 Anniversary Update, with version `0.7.1` of the PowerShell extension, the syntax highlighting inside this parameter attribute is incorrectly handled.

![image](https://cloud.githubusercontent.com/assets/466713/18104457/691a4514-6eb8-11e6-95ee-646bd7f8c3cf.png)
# Expected Result

The syntax highlighting should work consistently both inside and outside of a `[ValidateScript({ ... })]` parameter attribute.

https://github.com/PowerShell/vscode-powershell/issues/272

Cheers,
**Trevor Sullivan**
Docker Captain
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by daviwil** [comment]
Thanks Trevor! This may have been one of the things @gravejester fixed in the new syntax definition so we'll double check that before we roll it out again.

**Comment by omniomi** [comment]
Fixed by #94
