### ISSUE TITLE
PARAMETER keyword in comment based help not recognized

### ISSUE THREAD

**Issue by towerbe** [PowerShell/EditorSyntax#174]
### Environment
Version: 1.33.1 (user setup)
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:27:14.102Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

### Issue Description
When writing comment-based help, the ".PARAMETER" keyword does not get highlighted correctly.  All other keywords show up as white text, but .PARAMETER shows up in default comment color
#### Screenshots

![2019-05-10 11_13_10-Window](https://user-images.githubusercontent.com/17556410/57541447-abc70d80-7314-11e9-858f-62056b9ec05e.jpg)

### Expected Behavior

.PARAMETER should show up as white text like other keywords.

### Code Samples

```PowerShell

<#
    .NOTES
    .SYNOPSIS
    Enter a synopsis here
    .DESCRIPTION
    Enter a more detailed description here
    .LINK
    .INPUTS
    .OUTPUTS
    .PARAMETER
    .EXAMPLE
    .FUNCTIONALITY
#>
```

**Comment by msftrncs** [comment]
@towerbe, you are using the `.parameter` keyword incorrectly.  In order to be the `.parameter` comment based help keyword, the `.parameter` keyword must be followed by a parameter name.   Failure to do this will cause the entire comment block to be ignored for use as a help guide.  Notice GitHub's reaction in the code sample below compared to yours.

```PowerShell
<#
    .NOTES
    .SYNOPSIS
    Enter a synopsis here
    .DESCRIPTION
    Enter a more detailed description here
    .LINK
    .INPUTS
    .OUTPUTS
    .PARAMETER aParameterName
    .EXAMPLE
    .FUNCTIONALITY
#>
```

**Comment by towerbe** [comment]
Huh?  Now that you say that, I see the distinction in the documentation. 

Thanks.
