### ISSUE TITLE
Are there Powershell flag highlighting inconsistencies?

### ISSUE THREAD

**Issue by jrsconfitto** [PowerShell/EditorSyntax#18]
From @cosmo0 in [#26 (comment)](https://github.com/jugglingnutcase/language-powershell/issues/26#issuecomment-64531275):

> For the from/to problem: I have a method that I call like that:
> 
> ``` powershell
> Install-ConfigFiles -from "$here\tests\process" -to "$here"
> ```
> 
> The `-from` is highlighted, but the `-to` is white. With my color scheme (Monokai), `-from` is pink and `-to` is white.

Notice this is also visible on GitHub.com (as of OP).

_Copied from original issue: jugglingnutcase/language-powershell#24_

**Comment by jugglingnutcase** [comment]
From @cosmo0 in [#26 (comment)](https://github.com/jugglingnutcase/language-powershell/issues/26#issuecomment-64531275):

> For the from/to problem: I have a method that I call like that:

> ```powershell
> Install-ConfigFiles -from "$here\tests\process" -to "$here"
> ```

> The `-from` is highlighted, but the `-to` is white. With my color scheme (Monokai), `-from` is pink and `-to` is white.

Notice this is also visible on GitHub.com (as of OP).

**Comment by daviwil** [comment]
Thanks for copying those over!

**Comment by omniomi** [comment]
This is resolved as of #94
