### ISSUE TITLE
Function without arguments not colorized

### ISSUE THREAD

**Issue by gsscoder** [PowerShell/EditorSyntax#198]
This is a clone of this issue: https://github.com/PowerShell/vscode-powershell/issues/2558#event-3258201496.

Hi **vscode-powershell** team, thank you for great job!

It's more easy if I show you a screenshot:
![ps-colorcoding-vscode](https://user-images.githubusercontent.com/1194228/76704966-d3c59100-66dc-11ea-908f-d19cee0f2184.PNG)

I expect `ScriptName` function to be colorized with a color different from the rest of the string.

Have a nice day.

Regards,
Giacomo S. S.

**Comment by msftrncs** [comment]
This is a `meta.embedded` issue.   It is handled by PR #156 

![image](https://user-images.githubusercontent.com/26179051/109760897-27164500-7bb5-11eb-9c3f-c334d7dadc37.png)

**Comment by gsscoder** [comment]
OK, @msftrncs. Thank you
