### ISSUE TITLE
Improper syntax highlighting for #requires statement

### ISSUE THREAD

**Issue by pcgeek86** [PowerShell/EditorSyntax#20]
I have a PowerShell code file with two `#requires` statements. The code works properly, but the syntax highlighting is improper.

Specifically:
- The `-module` on the second `#requires` statement should be consistently colored. Right now, the dash is colored differently from the parameter name.
- The `ServerManager` argument should be colored consistently with parameter values, according to the current theme (this might be debatable)

![image](https://cloud.githubusercontent.com/assets/466713/18319771/6b5d8066-74e4-11e6-9f8f-f0bba0168ab8.png)

Cheers,
**Trevor Sullivan**
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by daviwil** [comment]
Thanks Trevor!  We'll get that fixed.

**Comment by sgtoj** [comment]
Relates issue with the `-Version` property: 

![PS Requires Version](http://i.imgur.com/yukdEss.png)
