### ISSUE TITLE
Parameters are shown using variables-color

### ISSUE THREAD

**Issue by fflaten** [PowerShell/EditorSyntax#203]
### Environment

- Editor and Version (VS Code, Atom, Sublime): VS Code
- Your primary theme: One Dark Pro 

### Issue Description

While semantic highlighting is enabled (theme default), parameters are shown using the same color as the variables, making it hard to split parameter from value. Literals are shown using their separate color as expected.

Also tested with Powershell ISE theme.

#### Screenshots

Semantic highlighting enabled:
![image](https://user-images.githubusercontent.com/3436158/109701573-751a5100-7b93-11eb-92c5-663f9554331a.png)
![image](https://user-images.githubusercontent.com/3436158/109701655-8b281180-7b93-11eb-9e90-874a8d309d0d.png)

### Expected Behavior

Variables and parameters should have different colors like before.

Semantic highlighting disabled in settings:
![image](https://user-images.githubusercontent.com/3436158/109701719-a004a500-7b93-11eb-8265-75d778f70ca7.png)
![image](https://user-images.githubusercontent.com/3436158/109701702-9aa75a80-7b93-11eb-8d64-1594c9ba06b3.png)

### Code Samples

```PowerShell
Get-ChildItem -Path $path -Filter $filter -Include 'literal value'
```

**Comment by bitdeft** [comment]
I came here to echo this issue. This seems to be related to the new semantic highlighting feature.
 Please update it so that the parameters use white or grey as they before. 

 Primary Theme: Dark+

**Comment by msftrncs** [comment]
white or grey is not the correct color!  That is a lack of color, and was caused by EditorSyntax choosing no scoping for those tokens.

However, that is up to your theme to choose the color, not for either EditorSyntax or the semantic tokenizer.   They only specify what an object is.

Here's how mine looks: (without semantic highlighting, and a custom PS grammar)
![image](https://user-images.githubusercontent.com/26179051/109755242-43ad7f80-7bab-11eb-9ff7-99a77d4d96cc.png)

**Comment by msftrncs** [comment]
Also, semantic token highlighting issues need to be taken over to https://github.com/PowerShell/vscode-powershell.  The semantic tokenizing is handled in the PowerShell extension, not in the basic language syntaxing module here.  The PowerShell ISE Theme also comes from there as well.

**Comment by fflaten** [comment]
@msftrncs I'm not sure how the picture of your theme without semantic helps. Maybe most/all themes forgot to color the parameters before, but the end result is that it worked. The issue is only when semantic is enabled. Are we sure the themes can separate the token types?

I was redirected here for "editor syntax colorization issues" in vscode-powershell's new issue template-menu. If that's wrong, you might want to make them rephrase or change that, because atm you both point at each other.

**Comment by fflaten** [comment]
Related PowerShell/vscode-powershell#3221

**Comment by andschwa** [comment]
@fflaten I've updated our FAQ to clarify the interaction between the extension's highlighting and the highlighting grammar (this repo): https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#problems-with-syntax-highlighting

Funnily enough, I've also updated the issue form on the extension...but GitHub still hasn't added us to the beta for new issue forms so it's still a draft PR: https://github.com/PowerShell/vscode-powershell/pull/3332

**Comment by fflaten** [comment]
Thanks @andschwa. I also noticed that the editor syntax-redirect in the issue template is removed in vscode-powershell 👍 
I've lately switched to Github Dark theme which works far better with semantic enabled. It has a lot more tokenColors defined which I guess help separate parameters and variables properly.
![image](https://user-images.githubusercontent.com/3436158/118600097-ca3c2b00-b7b0-11eb-8682-e06a4031114e.png)

Haven't looked into which tokenColor that fixed it, but I guess this might now be more of a theme-issue with "PowerShell ISE".

Btw. didn't know about the issue forms private beta). They look awesome!
