### ISSUE TITLE
Syntax highlighting doesn't recognize '#text' property

### ISSUE THREAD

**Issue by daviwil** [PowerShell/EditorSyntax#21]
Moving this issue over from PowerShell/vscode-powershell#238 for @stej.  @gravejester might have fixed this already in his new definition so we'll have to verify it once we get the test system running.

---

I have this code:

```
Get-SomeXml | 
Select-Object -ExpandProperty Node |
        % { if ($_.'#text') { $_.'#text'.Trim() -split ',\s*' }
            else            { @() }
        }
```

The syntax highlighter is confused from the ending apostrophe behind the `#text` property. 

![image](https://cloud.githubusercontent.com/assets/253560/17693228/183d8aea-639e-11e6-9d4e-078560d0aa31.png)

The problem is probably caused by the hash sigh `#`, because once I remove it, it is ok.

_Workaround_

```
$textProp = '#text' # just workaround because of syntax highlighter

Get-SomeXml | 
Select-Object -ExpandProperty Node |
        % { if ($_.$textProp) { $_.$textProp.Trim() -split ',\s*' }
            else            { @() }
        }
```

**Comment by omniomi** [comment]
This is resolved as of #94
