### ISSUE TITLE
Comments on same line as Function not styled when opening brace is on next line

### ISSUE THREAD

**Issue by fredskis** [PowerShell/EditorSyntax#30]
I ran into this issue using the PowerShell extension for VS Code and was referred to this project.

### Issue Description

When adding comments on the same line as a function where the opening brace is on the next line, the comment doesn't get formatted correctly. 
I'm using the Dark+ (default dark) theme and comments are green, however, when entered into this line they appear as grey.

As an example: 
```
Function New-Function { #comment here
}
```
formats fine with a green comment, however, 
```
Function New-Function #comment here
{
}
```
doesn't format correctly and the comment remains grey.

**Comment by omniomi** [comment]
Resolved by #94 

![comments](https://user-images.githubusercontent.com/12937335/40328576-0da973e4-5d04-11e8-90ec-b45f442f8bb3.png)
