### ISSUE TITLE
ValidatePattern breaking Syntax Highlighting

### ISSUE THREAD

**Issue by RobBiddle** [PowerShell/EditorSyntax#34]
Regex for GUID validation is breaking Syntax Highlighting

Add this to a Parameter statement to recreate issue: `[ValidatePattern("^(\{){0,1}[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}(\}){0,1}$")]`

VSCode 1.8.1
PowerShell extension 0.9.0

**Comment by tjsobeck** [comment]
Same issue with mac address validation
[Parameter(ParameterSetName='mac')][ValidatePattern("([a-zA-Z0-9]{2}:){5}[a-zA-Z0-9]{2}")]

**Comment by jbolduan** [comment]
I'm also seeing this issue on the following build:

VSCode 1.12.2
PowerShell Extension: 1.1.0

**Comment by MattAllison** [comment]
I think there are a handful of issues on this (including one I commented on a bit but can't seem to find).  Can we combine them?

**Comment by keller4** [comment]
Same issue with the following:

[ValidatePattern('^[A-Fa-f0-9]{8}-([A-Fa-f0-9]{4}-){3}[A-Fa-f0-9]{12}$')]

Everything following the final single-quote is displayed as though it were a string.

VSCode 1.14.2
PowerShell Extension 1.4.1

**Comment by thor** [comment]
Is there anything anyone can help with, besides the actual TextMate grammar update required, to aid this bug being fixed? :slightly_smiling_face:

**Comment by omniomi** [comment]
This was resolved by #94
