### ISSUE TITLE
Warning on assignment vs comparison in if statement

### ISSUE THREAD

**Issue by samr33** [PowerShell/EditorSyntax#35]
Hello,
Really loving the syntax highlighting in combo with VSCode. I've been looking for a way to defeat my ultimate Powershell enemy:
if\s*\\(\.*=.\*\\)
Any valid uses for this? Would a warning be warranted? Any way I can extend ISE or VSCode to do this?
Thanks in advance for consideration.

**Comment by daviwil** [comment]
Are you trying to remove whitespace from these statements?  You might appreciate a new code formatting rule that is coming in the next release which allows you to control this.

https://github.com/PowerShell/vscode-powershell/pull/489

**Comment by samr33** [comment]
Thanks! No, I'm trying to avoid writing the statement if ($a = $b) {do something} which in Powershell doesn't generate a syntax error, just does the assignment, but is clearly meant to be if ($a -eq $b) {do something}. Too many years of that overloaded equals sign being able to do comparisons in the right context, old habits die hard. It's a pretty tough bug to find for me, would be great to have a hint that it might be wrong, or a way to easily extend the hinting or error matching with regex configs.

**Comment by vors** [comment]
Please upvote corresponding issue in the script analyzer repo https://github.com/PowerShell/PSScriptAnalyzer/issues/809
