### ISSUE TITLE
Saving a Module Manifest (.psd1) renders it unuseable

### ISSUE THREAD

**Issue by PowellDean** [PowerShell/EditorSyntax#36]
Hi:

I am working with PowerShell modules (.psm1 files). As per best practice I am creating a manifest file (.psd1) for each module, using the built-in New-ModuleManifest cmdlet. I'm just generating relatively generic manifest files (no options fed into the cmdlet to customize), and then editing manually. Immediately after creating the manifest file, I display with "type MyModule.psd1" and see results like this:
<pre>
# Module manifest for Module MyModule'
#
# Generated By: blah
</pre>

Atom lists the file type at the bottom as "UTF-8" which should be fine, but if I delete characters, it actually takes 2 keystrokes to delete each. If I save the resulting .psd1 file, then use the standard Import-Module cmdlet, PowerShell complains the manifest is not in a correct format. If I then display the file through the command line again, I see:

<pre>
#  M o d u l e  m a n i f e s t  f o r  M o d u l e   M y M o d u l e ' 

#

#  G e n e r a t e d   B y :  b l a h 
</pre>

It appears Atom thinks .psd1 files are UTF-16 and  then saving as such, which PowerShell does not work well with.

I can provide examples if required. Is there a workaround for this?

**Comment by MovGP0** [comment]
I am wondering if this is really an issue of the file encoding or an issue with Atom. Can you reproduce this with another editor like VS Code?

**Comment by PowellDean** [comment]
Thank you for your reply. I have done some research and it is definitely an
issue of the file encoding. For reasons we are unable to fathom, the
Microsoft-supplied module for generating manifests specifically outputs the
manifest in UTF-16 format, even if the input format is UTF-8. To my mind,
there is no excuse for this and the Microsoft module is wrong.

It appears that Atom doesn't yet work very well with UTF-16. I can force
the encoding to UTF-16 (big-endian, if I remember the wording) but saving
the file in this format makes PowerShell refuse to work with it.

I am working my way through tutorials in an attempt to write a plug-in for
Atom that generates a manifest module in a new editor pane (and defaults
the file encoding to the same as the input file) but I simply haven't had
the time to devote to this yet. Plus, since I already hacked together a
similar process in Smalltalk (my language of choice) this is now a low
priority on my task list. If you are interested in seeing such a plug-in
please let me know and I'll assign a higher priority to it.

You can close the ticket. I appreciate your investigation.

Regards,
Dean Powell
Edmonton, Canada

**Comment by omniomi** [comment]
> You can close the ticket. I appreciate your investigation.
