### ISSUE TITLE
Syntax coloring issue with regex

### ISSUE THREAD

**Issue by daviwil** [PowerShell/EditorSyntax#37]
_From @fromthewoods on February 19, 2017 5:18_

I searched around and couldn't find any existing issues that address what I'm seeing, so apologies if this is already known.

I have a simple regex pattern `[ValidateScript({$_ -match '^([\d\w]+\.){2,3}[\d\w]+$'})]`
that vscode seems to not be able to handle and I assume it's an issue with PSEditorServices.
![image](https://cloud.githubusercontent.com/assets/5445673/23099888/57b1ac7e-f62e-11e6-9dec-101459052f48.png)

PowerShell ISE handles the same pattern properly.
![image](https://cloud.githubusercontent.com/assets/5445673/23099889/65633cac-f62e-11e6-816d-36f6ff88c990.png)

_Copied from original issue: PowerShell/PowerShellEditorServices#374_

**Comment by daviwil** [comment]
_From @fromthewoods on February 28, 2017 22:25_

Did I put this in the wrong repo? Should this be in [PowerShell / vscode-powershell](https://github.com/PowerShell/vscode-powershell) or [Microsoft / vscode](https://github.com/Microsoft/vscode) ?

**Comment by daviwil** [comment]
_From @rkeithhill on February 28, 2017 22:26_

It should go in https://github.com/powershell/editorsyntax.

**Comment by fromthewoods** [comment]
Thanks @daviwil and @rkeithhill.

**Comment by fromthewoods** [comment]
Windows 7
VScode 1.9.1
PowerShell extension 0.9.0
PowerShell version 5.1.14409.1005

**Comment by MattAllison** [comment]
I'm having the same problem.  Patterns in question are:

        [Parameter(Mandatory=$True,ValueFromPipelineByPropertyName=$True )]
        [ValidatePattern("^((?!^.{90})([A-Z]{2}(-)[0-9]+-[0-9]+-[A-Z]{4}-RG-[0-9]+))$")]
        [string]$Parameter1,          
           
        [Parameter(Mandatory=$true,ValueFromPipelineByPropertyName=$True)]
        [ValidatePattern("^((?!^.{80})([A-Z]{2}(-)[0-9]+-[0-9]+-[A-Z]{4}-LB-[0-9]+))$")]
        [string]$Parameter2,

**Comment by Jawz84** [comment]
First off; thanks for all the hard work!!
Wanted to let you know: i have this issue too:
`
[Parameter(ParameterSetName = 'Network')]
        [ValidatePattern('^(([2]([0-4][0-9]|[5][0-5])|[0-1]?[0-9]?[0-9])[.]){3}(([2]([0-4][0-9]|[5][0-5])|[0-1]?[0-9]?[0-9]))(\/[1-3]?[1-9])?$')]
        [string]$IpAddress,
`
code -v: 
1.12.2 
19222cdc84ce72202478ba1cec5cb557b71163de
$pseditor.EditorServicesVersion: 
1.2.1.0
$PSVersionTable: 
Name                           Value
PSVersion                      5.1.15063.296
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.296
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by keller4** [comment]
Wonderful project. I almost hate to bring it up, but having syntax coloring problem. Regex seems to break it, and it doesn't come back until there's a comment with a single quote in it.
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 
Extension|Author (truncated)|Version
PowerShell|ms-|1.5.1

Example:
function test
{
    param(
        # Using customer IDs filter
        [Parameter(Mandatory=$false,
                   ParameterSetName='Search')]
        [ValidatePattern('^[A-Fa-f0-9]{8}-([A-Fa-f0-9]{4}-){3}[A-Fa-f0-9]{12}$')]
        [string]
        $UsingCustomerIDs
    )
    # Comment with ' in it
    Get-ChildItem c:\
}
![image](https://user-images.githubusercontent.com/30486379/32985733-09b7528e-cc8f-11e7-97ac-89e5c69d6a15.png)

**Comment by omniomi** [comment]
Fixed by #94
