### ISSUE TITLE
Request: Syntax coloring and intellisense for integrated console?

### ISSUE THREAD

**Issue by cobdev** [PowerShell/EditorSyntax#41]
I'm loving the new integrated console!

Maybe I'm missing something in my configuration, but could the integrated console provide syntax coloring and intellisense in the future?

Thank you!

![2017_03_17_15_18_07_greenshot](https://cloud.githubusercontent.com/assets/10552026/24065024/4f96621c-0b25-11e7-9af6-27f3e659120c.png)

**Comment by daviwil** [comment]
This will be enabled once we get PSReadline hooked up in the integrated console, track this issue to know when that comes online: https://github.com/PowerShell/vscode-powershell/issues/535
