### ISSUE TITLE
Discrepancy in Syntax coloring of some cmdlets in VSCode

### ISSUE THREAD

**Issue by PrateekKumarSingh** [PowerShell/EditorSyntax#42]
### System Details

- Operating system name and version: Windows 10, version 1607
- VS Code version: 1.10.2
- PowerShell extension version: 0.11.0
- Output from `$PSVersionTable`:

```

Name                           Value                                                                                                                                                                  
----                           -----                                                                                                                                                                  
PSVersion                      5.1.14393.693                                                                                                                                                          
PSEdition                      Desktop                                                                                                                                                                
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                
BuildVersion                   10.0.14393.693                                                                                                                                                         
CLRVersion                     4.0.30319.42000                                                                                                                                                        
WSManStackVersion              3.0                                                                                                                                                                    
PSRemotingProtocolVersion      2.3                                                                                                                                                                    
SerializationVersion           1.1.0.1                                                                                                                                                                


```

### Issue Description

Some Cmdlets are not color coded like they are supposed to in the editor pane of VSCode with default or any theme, 

Cmdlets with issue - Tee-Object, Where-Object, Sort-object, could be more

![image](https://cloud.githubusercontent.com/assets/13902553/24239050/617c992c-0fd2-11e7-85f0-54b32e7d5e4b.png)

![image](https://cloud.githubusercontent.com/assets/13902553/24241483/026490bc-0fdb-11e7-86f9-7eb70134318a.png)

A catch here could be all these cmdlets with coloring issues have an Alias same as the "Verb" in the Verb-Noun Syntax of the cmdlet, like Sort for Sort-Object

![image](https://cloud.githubusercontent.com/assets/13902553/24241613/68e66284-0fdb-11e7-9d06-2b323b141c13.png)

Run below one liner from vs code and see the difference in color of some cmdlets -
```
gcm|% name|?{$_ -like "*-*"} >TestFile.ps1;code .\TestFile.ps1
```

**Comment by pcgeek86** [comment]
I can confirm that `Sort-Object` is not properly being highlighted.

![screen shot 2017-04-17 at 8 38 38 am](https://cloud.githubusercontent.com/assets/466713/25093883/4d49d96c-2349-11e7-9121-8c65e85c087c.png)

Cheers,
Trevor Sullivan

**Comment by MovGP0** [comment]
same issue as #39

**Comment by omniomi** [comment]
This is resolved as of the latest commit to master.
