### ISSUE TITLE
Feature Request:  Have the integrated terminal pull the vscode theme coloring into it.

### ISSUE THREAD

**Issue by klocke7** [PowerShell/EditorSyntax#44]
Would it be possible to have the PowerShell integrated terminal pull the theme colors for code from the vscode theme?  This way whatever theme is selected for vscode the same code color would be replicated in side the integrated terminal?

**Comment by daviwil** [comment]
This will happen in VS Code starting in the 1.11.0 release: https://twitter.com/Tyriar/status/849478844805459972
