### ISSUE TITLE
.bat & .exe Syntax Highlighting Error

### ISSUE THREAD

**Issue by ThmsRynr** [PowerShell/EditorSyntax#46]
There's syntax highlighting to indicate commands which makes things like `something.bat` and `ipconfig.exe` the same color as PowerShell cmdlets like `import-module`. The highlighting for .bat and .exe files doesn't properly detect when .bat or .exe is part of a longer word.

## Code to reproduce
```something.bat 
ipconfig.exe
Import-Module AzureRM.Backup
Import-Module AzureRm.Batch 
Import-Module AzureRm.Exefake
Import-Module AzureRM.Cdn
```

## Result of code
Using Monokai Dimmed theme for emphasis.
![image](https://cloud.githubusercontent.com/assets/13203965/25147973/8fb4a352-2436-11e7-8b0b-d85ba8aee219.png)
Lines 4 and 5 have incorrect syntax highlighting.

## Diagnostic info
```code --list-extensions --show-versions
ms-vscode.PowerShell@0.11.0
ms-vsts.team@1.115.0
msazurermtools.azurerm-vscode-tools@0.3.4
yanz.markdown-authoring@0.1.5

code -v
1.11.2
6eaebe3b9c70406d67c97779468c324a7a95db0e

$PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14393.1066
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.1066
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by MovGP0** [comment]
this can be reproduced on GitHub too: 
```powershell
ipconfig.exe
Import-Module AzureRM.Backup
Import-Module AzureRm.Batch 
Import-Module AzureRm.Exefake
Import-Module AzureRM.Cdn
```
Seems to be the related to #39

**Comment by omniomi** [comment]
As of the most recent commit this is fixed:

![fixed3](https://user-images.githubusercontent.com/12937335/40328017-20022420-5d02-11e8-8382-5c15f4edaa49.png)
