### ISSUE TITLE
Operator vs. Parameter Color Coding Issue

### ISSUE THREAD

**Issue by GoateePFE** [PowerShell/EditorSyntax#54]
$x = 100000
$EmailList = For ($i=0;$i -lt $x;$i++) {
    "$(Get-RandomString -length 10)@$(Get-RandomString -length 10).com"
}
$EmailList | Set-Content -Path .\file1.txt

In the above code sample "-le" is highlighted in a different color than the rest of the string. "-Length" is a parameter of a helper function in the same script.

**Comment by omniomi** [comment]
Fixed in PR #97 

![length](https://user-images.githubusercontent.com/12937335/40327029-a0115b8a-5cfe-11e8-9bbe-0456ac184ab0.png)
