### ISSUE TITLE
Incorrect coloring of PowerShell call operator line with "#" character in arguments

### ISSUE THREAD

**Issue by sandersaares** [PowerShell/EditorSyntax#55]
The following line is incorrectly colored:

```
& $oscdimg -m -o -u2 -udfver102 -bootdata:2#p0,e,b$isoPath\boot\etfsboot.com#pEF,e,b$isoPath\efi\microsoft\boot\efisys.bin $isoPath $outputPath
```

VS Code treats the first "#" as the start of a comment, whereas it really is just a part of the command arguments passed to the call operator.

See also: https://github.com/PowerShell/vscode-powershell/issues/974

**Comment by omniomi** [comment]
This is related to #62

**Comment by tylerl0706** [comment]
We can close it as a due of #62
