### ISSUE TITLE
Implement a CI/CD pipeline

### ISSUE THREAD

**Issue by gravejester** [PowerShell/EditorSyntax#58]
We should automate the build and the tests using a CI/CD pipeline

**Comment by gravejester** [comment]
@daviwil have set up the project in AppVeyor.

At the moment the build script running don't really gives us anything - as we are not pushing anything back to the repository.

Should we set it up so that when we use tags, the build will run and AppVeyor can publish a new version in GitHub with the grammar files as either standalone files or a zipped package?

**Comment by daviwil** [comment]
That's certainly a possibility, since we don't need to worry about digitally signing these files we could automate the whole "release" process.  I haven't tried using the GitHub Release APIs yet so I'm not sure how much work it'd take.

**Comment by gravejester** [comment]
It's not a high priority right now, but when I'm getting done with the tests I can give it a shot - unless you beat me to it :)

**Comment by omniomi** [comment]
@gravejester I am going to close this as the current commit in master include build and tests steps and Appveyor for CI. We can open additional issues to make specific changes to the CI.
