### ISSUE TITLE
Discussion: How to handle parameters

### ISSUE THREAD

**Issue by gravejester** [PowerShell/EditorSyntax#6]
Hi, another topic for discussion, or rather I need some feedback on how to handle syntax highlighting of parameters, more specifically of the form `-Parameter`.

At the moment I have just created a very generic parameter match that highlights any occurrence of `-text` as a parameter.

This is not really ideal, as stuff like `$a -foobar -$b` are highlighted as a parameter. The only positive thing about this really, is that the regex is very short and easy :)

But my guess is that we should work to get parameter highlighting a bit better than this.

The tmlanguage format are kind of limiting when it comes to really complicated matching, but I *think* this is do-able, as long as we can clearly define a start and end for a command statement.

This is where I need your input. Is it correct to say that:
- A command starts with either (Verb-Noun) or (alias) or (foreach-object | tee-object | where-object | sort-object)
- A command ends with either (End of line/string) or ('|' - the pipe character)

Any cases I have not thought about?

I have written some test-code that I will use to test the matching rules,again if you have any input or additions to this, please let me know. The more unique examples the better!

https://gist.github.com/gravejester/0f90a887c3765771ebc15a94120cbdeb

 @daviwil @jaykul @kirkmunro @rkeithhill @vors

**Comment by rkeithhill** [comment]
A command does not end with end of line *if* the last character is a backtick.  

It might be easier to default to parameter colorization unless the `-<token>` matches one of the PowerShell operators.  That list is long but manageable, I think.  This approach has the unfortunate consequence of misrepresenting parameters that have the same name as a built-in operator.  Not sure if that is an "acceptable loss" or not.  :-)

**Comment by vors** [comment]
@rkeithhill That's pretty match how it's done right now. List of tokens already [there](https://github.com/PowerShell/EditorSyntax/blob/master/PowerShellSyntax.tmLanguage#L280) (and around this line).
There is one difference: default for parameter names is "no-colorization" unless it matches `-<token>`. Then there is unfortunate collision.

@gravejester I really like idea of trying define commands regions. This generalization will help not only with parameters matching, but with other things as well. We can start with you described algorithm (+ back-tick) and see how it holds on the real world programs.

**Comment by gravejester** [comment]
@rkeithhill It might be simpler than you think (though I'd have to do some testing to be sure), because since we are defining start and end tokens, we can do matching across multiple lines (as opposed to when we are doing simple matching that only works per line).

So by saying that a command region starts at Verb-Noun and ends at either a pipeline or the end of the line, we don't have to worry about the back-tick at all, other than as an escape character. Well, that is not entirely true, as after a back-tick there would always have to be a end-of-line character, so we would have to let the matching regex ignore that if a back-tick is before it. But I think this is all do-able.

@vors So I guess the only way of being sure about this is to actually do some testing, so I will do that and give you some examples of the result, and we can decide if it's good enough or not :)

**Comment by gravejester** [comment]
I'll rephrase the command region as suck to take into account the back-tick:

- A command starts with either (Verb-Noun) or (alias) or (foreach-object | tee-object | where-object | sort-object)
- A command ends with either (End of line/string, except if it follows a back-tic) or ('|' - the pipe character)

**Comment by vors** [comment]
There are complications, like you need to handle `()` correctly (in regards for `|`), because somebody can do

```powershell
Get-Foo (1..20 | Out-String) -Param2 "param2"
```

**Comment by gravejester** [comment]
Hmm.. good point. That might make actually be what breaks it, but I'll give it a shot anyway :)

We'll always have the suggestion from @rkeithhill as a backup plan.

**Comment by gravejester** [comment]
Ok, I have done some testing, and I think I have finally got it working. I just have to look for regressions.

It was a bit tricky to get the end-of-line-except-right-after-backtick to work properly. I used $ to end at end-of-line but this doesn't actually consume the end-of-line, which tripped me up for a while. Had to use \r and \n instead.

**Comment by gravejester** [comment]
Had to do some minor changes to get rid of some small regressions, but seems to work as intended now.
