### ISSUE TITLE
[powershell] Line comment block not recognized in PowerShell when in attribute definition scope

### ISSUE THREAD

**Issue by aeschli** [PowerShell/EditorSyntax#64]
_From @dreadris on July 4, 2016 14:23_

- VSCode Version: 1.2.1
- OS Version: Windows 10

Steps to Reproduce:
1. Create a powershell script file (ie. test.ps1)
2. Open the script in vs code
3. Paste the following:
   `param(
   [ValidateScript(
       { if (Test-Path $_) { $True } else { Throw "Path:`"$_`" does not exist" } }
   )] 
   [string]$rootPath = "./"
   )`
4. Insert the # sign after ValidateScript( - the text style won't be changed to indicate the commented block.

_Copied from original issue: Microsoft/vscode#8730_

**Comment by omniomi** [comment]
Fixed by #94
